# == Global project settings ===========================================

name:             ggnpc-features
description:      ''
attribution:      'Map Data © OpenStreetMap'
bounds:           [-123.640, 36.791, -121.025, 38.719]
center:           [-122.5369, 37.8704, 13]
format:           png
interactivity:    false
minzoom:          6
maxzoom:          20
srs:              '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'
metatile:         1


# == Layer & Datasource defaults =======================================

_layer_default:   &layer
  'srs-name':     '900913'
  srs:            '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'

_pg_default:      &postgis
  type:           postgis
  dbname:         '{{dbname}}'
  host:           '{{dbhost}}'
  user:           '{{dbuser}}'
  password:       '{{dbpassword}}'
  port:           '{{dbport}}'
  geometry_field: way
  extent:         '-13763541.8416803, 4410014.78335954, -13472441.3732559, 4681500.2899002'
  srs:            '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'
  srid:           900913


# == Stylesheets =======================================================

Stylesheet:
  - map.mss
  - roads.mss


# == Layers ============================================================

Layer:

  # ---- Water (lines) (NHD) -------------------------------------------

  - <<: *layer
    name: water-lines
    id:   water-lines
    status: on
    properties:
      minzoom: 14
    Datasource:
      <<: *postgis
      geometry_field: geom
      table: >
        (
          SELECT geom
          FROM nhdflowline
          WHERE geom && !bbox!
        ) AS _

  # ---- Water (NHD) ---------------------------------------------------

  - <<: *layer
    name: water
    id:   water
    status: on
    Datasource:
      <<: *postgis
      geometry_field: geom
      table: >
        (
            SELECT ftype, ST_Collect(geom) AS geom
            FROM nhdwaterbody
            WHERE geom && !bbox!
              AND fcode IN (
                39000, -- Lake/Pond
                39004, -- Lake/Pond: Hydrographic Category = Perennial
                39009, -- Lake/Pond: Hydrographic Category = Perennial; Stage = Average Water Elevation
                39010, -- Lake/Pond: Hydrographic Category = Perennial; Stage = Normal Pool
                39011, -- Lake/Pond: Hydrographic Category = Perennial; Stage = Date of Photography
                39012, -- Lake/Pond: Hydrographic Category = Perennial; Stage = Spillway Elevation

                43600, -- Reservoir
                43601, -- Reservoir: Reservoir Type = Aquaculture
                43603, -- Reservoir: Reservoir Type = Decorative Pool
                43604, -- Reservoir: Reservoir Type = Tailings Pond; Construction Material = Earthen
                43605, -- Reservoir: Reservoir Type = Tailings Pond
                43606, -- Reservoir: Reservoir Type = Disposal
                43607, -- Reservoir: Reservoir Type = Evaporator
                43608, -- Reservoir: Reservoir Type = Swimming Pool
                43609, -- Reservoir: Reservoir Type = Cooling Pond
                43610, -- Reservoir: Reservoir Type = Filtration Pond
                43611, -- Reservoir: Reservoir Type = Settling Pond
                43612, -- Reservoir: Reservoir Type = Sewage Treatment Pond
                43613, -- Reservoir: Reservoir Type = Water Storage; Construction Material = Nonearthen
                43614, -- Reservoir: Reservoir Type = Water Storage; Construction Material = Earthen; Hydrographic Category = Intermittent
                43615, -- Reservoir: Reservoir Type = Water Storage; Construction Material = Earthen; Hydrographic Category = Perennial
                43617, -- Reservoir: Reservoir Type = Water Storage
                43618, -- Reservoir: Construction Material = Earthen
                43619, -- Reservoir: Construction Material = Nonearthen
                43621, -- Reservoir: Reservoir Type = Water Storage; Hydrographic Category = Perennial
                43623, -- Reservoir: Reservoir Type = Evaporator; Construction Material = Earthen
                43624, -- Reservoir; Reservoir Type = Treatment
                43625, -- Reservoir: Reservoir Type = Disposal; Construction Material = Earthen
                43626, -- Reservoir: Reservoir Type = Disposal; Construction Material = Nonearthen

                46600, -- Swamp/Marsh
                46601, -- Swamp/Marsh: Hydrographic Category = Intermittent
                46602, -- Swamp/Marsh: Hydrographic Category = Perennial

                 -1
              )
            GROUP BY ftype
          UNION
            SELECT ftype, ST_Collect(geom) AS geom
            FROM nhdarea
            WHERE geom && !bbox!
              AND fcode IN (
                33600, -- Canal/Ditch
                33601, -- Canal/Ditch: Canal/Ditch Type = Aqueduct

                44500, -- Sea/Ocean

                45500, -- Spillway

                46000, -- Stream/River
                46006, -- Stream/River: Hydrographic Category = Perennial

                 -1
              )
            GROUP BY ftype
          UNION
            SELECT 445, geom
            FROM water_fill
            WHERE geom && !bbox!
        ) AS _

  # ---- Coastline (NHD) -----------------------------------------------

  - <<: *layer
    name: coastline
    id:   coastline
    status: on
    Datasource:
      <<: *postgis
      geometry_field: geom
      table: >
        (
          SELECT ST_Union(geom) AS geom, SUM(areasqkm) AS areasqkm FROM (
              SELECT geom, areasqkm
              FROM nhdwaterbody
              WHERE geom && !bbox!
                AND fcode IN (
                  39000, -- Lake/Pond
                  39004, -- Lake/Pond: Hydrographic Category = Perennial
                  39009, -- Lake/Pond: Hydrographic Category = Perennial; Stage = Average Water Elevation
                  39010, -- Lake/Pond: Hydrographic Category = Perennial; Stage = Normal Pool
                  39011, -- Lake/Pond: Hydrographic Category = Perennial; Stage = Date of Photography
                  39012, -- Lake/Pond: Hydrographic Category = Perennial; Stage = Spillway Elevation

                  43600, -- Reservoir
                  43601, -- Reservoir: Reservoir Type = Aquaculture
                  43603, -- Reservoir: Reservoir Type = Decorative Pool
                  43604, -- Reservoir: Reservoir Type = Tailings Pond; Construction Material = Earthen
                  43605, -- Reservoir: Reservoir Type = Tailings Pond
                  43606, -- Reservoir: Reservoir Type = Disposal
                  43607, -- Reservoir: Reservoir Type = Evaporator
                  43608, -- Reservoir: Reservoir Type = Swimming Pool
                  43609, -- Reservoir: Reservoir Type = Cooling Pond
                  43610, -- Reservoir: Reservoir Type = Filtration Pond
                  43611, -- Reservoir: Reservoir Type = Settling Pond
                  43612, -- Reservoir: Reservoir Type = Sewage Treatment Pond
                  43613, -- Reservoir: Reservoir Type = Water Storage; Construction Material = Nonearthen
                  43614, -- Reservoir: Reservoir Type = Water Storage; Construction Material = Earthen; Hydrographic Category = Intermittent
                  43615, -- Reservoir: Reservoir Type = Water Storage; Construction Material = Earthen; Hydrographic Category = Perennial
                  43617, -- Reservoir: Reservoir Type = Water Storage
                  43618, -- Reservoir: Construction Material = Earthen
                  43619, -- Reservoir: Construction Material = Nonearthen
                  43621, -- Reservoir: Reservoir Type = Water Storage; Hydrographic Category = Perennial
                  43623, -- Reservoir: Reservoir Type = Evaporator; Construction Material = Earthen
                  43624, -- Reservoir; Reservoir Type = Treatment
                  43625, -- Reservoir: Reservoir Type = Disposal; Construction Material = Earthen
                  43626, -- Reservoir: Reservoir Type = Disposal; Construction Material = Nonearthen

                  -1
                )
            UNION
              SELECT geom, 9999
              FROM nhdarea
              WHERE geom && !bbox!
                AND fcode IN (
                  33600, -- Canal/Ditch
                  33601, -- Canal/Ditch: Canal/Ditch Type = Aqueduct

                  44500, -- Sea/Ocean

                  45500, -- Spillway

                  46000, -- Stream/River
                  46006, -- Stream/River: Hydrographic Category = Perennial

                  -1
                )
            UNION
              SELECT geom, 9999
              FROM water_fill
              WHERE geom && !bbox!
          ) AS _
          -- TODO zoom-dependent factor (0.075 makes sense at z14)
          WHERE areasqkm >= 0.075
        ) AS _

  # ---- GGNRA Boundaries (offshore) -----------------------------------

  - <<: *layer
    name: offshore-boundaries
    id:   offshore-boundaries
    status: on
    properties:
      minzoom: 12
    Datasource:
      <<: *postgis
      geometry_field: geom
      table: >
        (
          SELECT geom
          FROM ggnra_offshore_boundaries
          WHERE geom && !bbox!
        ) AS _

  # ---- Ferries--------------------------------------------------------

  - <<: *layer
    name: ferry
    id:   ferry
    properties:
      minzoom: 11
    Datasource:
      <<: *postgis
      table: >
        (
          SELECT way
          FROM planet_osm_line
          WHERE way && !bbox!
            AND tags @> 'route=>ferry'
          ORDER BY z_order ASC
        ) AS _

  # ---- Roads ---------------------------------------------------------

  - <<: *layer
    name: road_z6-8
    id:   road_z6-8
    class: road
    properties:
      cache-features: on
      minzoom: 6
      maxzoom: 8
    Datasource:
      <<: *postgis
      table: >
        (
          SELECT tags -> 'highway' AS highway,
            tags -> 'aeroway' AS aeroway,
            (CASE
            WHEN tags ? 'bridge' AND tags -> 'bridge' NOT IN ('no', 'false') THEN 'yes'
            ELSE NULL
            END) bridge,
            (CASE
            WHEN tags ? 'tunnel' AND tags -> 'tunnel' NOT IN ('no', 'false') THEN 'yes'
            ELSE NULL
            END) tunnel,
            way
          FROM planet_osm_line
          WHERE way && !bbox!
            AND tags -> 'highway' IN ('motorway', 'trunk')
            AND (NOT tags ? 'access' OR tags -> 'access' NOT IN ('no', 'false'))
          ORDER BY z_order ASC
        ) AS _

  - <<: *layer
    name: road_z9
    id:   road_z9
    class: road
    properties:
      cache-features: on
      minzoom: 9
      maxzoom: 9
    Datasource:
      <<: *postgis
      table: >
        (
          SELECT tags -> 'highway' AS highway,
            tags -> 'aeroway' AS aeroway,
            (CASE
            WHEN tags ? 'bridge' AND tags -> 'bridge' NOT IN ('no', 'false') THEN 'yes'
            ELSE NULL
            END) bridge,
            (CASE
            WHEN tags ? 'tunnel' AND tags -> 'tunnel' NOT IN ('no', 'false') THEN 'yes'
            ELSE NULL
            END) tunnel,
            way
          FROM planet_osm_line
          WHERE way && !bbox!
            AND tags -> 'highway' IN ('motorway', 'trunk', 'primary')
            AND (NOT tags ? 'access' OR tags -> 'access' NOT IN ('no', 'false'))
          ORDER BY z_order ASC
        ) AS _

  - <<: *layer
    name: road_z10
    id:   road_z10
    class: road
    properties:
      cache-features: on
      minzoom: 10
      maxzoom: 10
    Datasource:
      <<: *postgis
      table: >
        (
          SELECT tags -> 'highway' AS highway,
            tags -> 'aeroway' AS aeroway,
            (CASE
            WHEN tags ? 'bridge' AND tags -> 'bridge' NOT IN ('no', 'false') THEN 'yes'
            ELSE NULL
            END) bridge,
            (CASE
            WHEN tags ? 'tunnel' AND tags -> 'tunnel' NOT IN ('no', 'false') THEN 'yes'
            ELSE NULL
            END) tunnel,
            way
          FROM planet_osm_line
          WHERE way && !bbox!
            AND tags -> 'highway' IN ('motorway', 'trunk', 'primary', 'secondary', 'tertiary')
            AND (NOT tags ? 'access' OR tags -> 'access' NOT IN ('no', 'false'))
          ORDER BY z_order ASC
        ) AS _

  - <<: *layer
    name: road_z11-13
    id:   road_z11-13
    class: road
    properties:
      cache-features: on
      minzoom: 11
      maxzoom: 13
    Datasource:
      <<: *postgis
      table: >
        (
          SELECT tags -> 'highway' AS highway,
            tags -> 'aeroway' AS aeroway,
            (CASE
            WHEN tags ? 'bridge' AND tags -> 'bridge' NOT IN ('no', 'false') THEN 'yes'
            ELSE NULL
            END) bridge,
            (CASE
            WHEN tags ? 'tunnel' AND tags -> 'tunnel' NOT IN ('no', 'false') THEN 'yes'
            ELSE NULL
            END) tunnel,
            way
          FROM planet_osm_line
          WHERE way && !bbox!
            AND 
              (tags -> 'highway' IN ('motorway', 'trunk', 'primary',
                                     'secondary', 'tertiary', 'residential',
                                     'unclassified', 'service', 'road')
              AND (NOT tags ? 'access' OR tags -> 'access' NOT IN ('no', 'false')))
            OR
              (tags ? 'aeroway' AND tags -> 'aeroway' IN ('runway', 'taxiway'))
          ORDER BY z_order ASC
        ) AS _

  - <<: *layer
    name: road_z14plus
    id:   road_z14plus
    class: road
    properties:
      cache-features: on
      minzoom: 14
    Datasource:
      <<: *postgis
      table: >
        (
          SELECT tags -> 'highway' AS highway,
            tags -> 'aeroway' AS aeroway,
            (CASE
            WHEN tags ? 'bridge' AND tags -> 'bridge' NOT IN ('no', 'false') THEN 'yes'
            ELSE NULL
            END) bridge,
            (CASE
            WHEN tags ? 'tunnel' AND tags -> 'tunnel' NOT IN ('no', 'false') THEN 'yes'
            ELSE NULL
            END) tunnel,
            way
          FROM planet_osm_line
          WHERE way && !bbox!
            AND
              (tags ? 'highway'
                AND tags -> 'highway' IN ('motorway', 'trunk', 'primary',
                                          'motorway_link', 'trunk_link', 'primary_link',
                                          'secondary_link', 'tertiary_link',
                                          'secondary', 'tertiary', 'residential',
                                          'unclassified', 'service', 'road')
                AND
                (NOT tags ? 'access' OR tags -> 'access' NOT IN ('no', 'false')))
              OR
              (tags ? 'aeroway' AND tags -> 'aeroway' IN ('runway', 'taxiway'))
          ORDER BY z_order ASC
        ) AS _

  # ---- Buildings -----------------------------------------------------

  - <<: *layer
    name: buildings
    id:   buildings
    status: on
    properties:
      minzoom: 15
    Datasource:
      <<: *postgis
      geometry_field: geom
      table: >
        (
          SELECT geom,
            (CASE
            WHEN name ILIKE 'battery %' THEN true
            ELSE false
            END) battery
          FROM ggnra_buildings
          WHERE geom && !bbox!
        ) AS _

  # ---- Trails --------------------------------------------------------

  - <<: *layer
    name: trails
    id:   trails
    status: on
    properties:
      minzoom: 13
      cache-features: on
    Datasource:
      <<: *postgis
      geometry_field: geom
      table: >
        (
          SELECT *
          FROM trails
          WHERE geom && !bbox!
        ) AS _

